resources:
  repositories:
    - repository: templates-pipeline
      type: git
      name: '00_TEMPLATE_YML/templates-pipeline'

stages:
  - template: azure-pipelines.yml@templates-pipeline
    parameters:
      branchToMonitor: 'main'
      emailsNotificacao: 'valahiguera@senacrs.com.br'
      enableEmailNotification: true